### PR TITLE
Return updated `base_circuit` from `append!` & `prepend!`.

### PR DESCRIPTION
**Pull request by ps-pat**
This would make those methods behave like their counterparts in Base. Also, it would allow the use of the `@chain` macro.

### CODE REVIEW

**Review by plerouxanyon — APPROVED** [review]

**Comment by plerouxanyon** [comment]
Thank you for your contribution! It looks good to me! I'll merge when the CI/CD passes.

**Comment by plerouxanyon** [comment]
It seems the documentation comments need updating before this can proceed.

**Comment by ps-pat** [comment]
> It seems the documentation comments need updating before this can proceed.

Alright I'm on it.

**Comment by ps-pat** [comment]
Also it seems to me that `apply_gate!` should return as well. Should I modify it as well?

**Comment by plerouxanyon** [comment]
> Alright I'm on it.

Thanks!

> Also it seems to me that `apply_gate!` should return as well. Should I modify it as well?

That would be great!

**Comment by plerouxanyon** [comment]
Thank you very much for the change!

**Pull request merged**
